# Use lightweight Python image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy scripts
COPY scripts/ ./scripts/

# Default command (date argument should be passed dynamically in ECS)
CMD [ "python", "./scripts/ingest_polygon.py" ]